name: API Tests

on:
  push:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Run API tests
        run: newman run "dummyjson-collection.json" -e "dummyjson-environment.json" -r cli,json --reporter-json-export "newman-report.json"

      - name: Upload Newman report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.json